### ISSUE TITLE
Add view & log changes globally

### ISSUE THREAD

**Issue by S1SYPHOS** [bnomei/kirby3-recently-modified#1]
.. so one could track changes made by users, restricted by role

**Comment by bnomei** [comment]
hi @S1SYPHOS .
i added the pagemethod `findRecentlyModifiedByUser` recently. haha pun intended. so the following should work.

```yaml
sections:
  recentarticles:
    type: recentlymodified
    headline: Recently Modified Articles
    # query: site.index(true).sortBy('modified', 'desc') # all pages here or as php setting
```

```php
return [
    'bnomei.recently-modified.query' => "site.index(true).sortBy('modified', 'desc')", // all pages
    'bnomei.recently-modified.limit' => 10000, // track 10k pages globally
    'bnomei.recently-modified.info' => function ($page) {
        $user = $page->findRecentlyModifiedByUser(); // ?User
        return ($user ? $user->nameOrEmail() : '') . ' | ' $page->modified();
    },
    // other options...
];
```

this will show a list of all pages sorted by modified timestamp and which user changed it most recenlty. if you want to list the last few editors for a single page, not just the most recent editor, then take a look at the `findRecentlyModifiedByUser` pagemethod and just build your own based on that.
